version: "3.7"

services:

   sqlserver:
     restart: unless-stopped
     environment:
       - SA_PASSWORD=P@ssw0rd
       - ACCEPT_EULA=Y
     ports:
       - "1433:1433"

   redis:
     ports:
       - "6379:6379"